### ISSUE TITLE
virtualbox-modules ne s'installe pas

### ISSUE THREAD

**Issue by wamuu-sudo** [wamuu-sudo/orchid#2]
/var/tmp/portage/app-emulation/virtualbox-modules-6.1.28/work/vboxdrv/include/iprt/types.h:134:12: fatal error: stddef.h: No such file or directory
  134 | #  include <stddef.h>
Failed to emerge app-emulation/virtualbox-modules-6.1.28

**Comment by juliiine** [comment]
Virtualbox-modules is not compatible with 5.16.11 kernel. Please use libvirt/qemu alternative.
