### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Plexvola** [wamuu-sudo/orchid#3]
Hello ! J'adore le projet !
Une distribution Gentoo, fleurie, et en français, ça coche toutes les bonnes cases.
Du coup, ce serait un plaisir de pouvoir aider au développement, si c'est possible :)

**Comment by wamuu-sudo** [comment]
Salut,
Merci de ton retour.
Y'a pas de soucis pour collaborer je pense voir pour créer un serveur Discord, ça sera plus simple.
Le projet n'en est qu'à ses débuts.
